import os
import sys
import avrconfig
from building import *

env = Environment(tools = ['mingw'],
    AS = avrconfig.AS, ASFLAGS = avrconfig.AFLAGS,
	CC = avrconfig.CC, CCFLAGS = avrconfig.CFLAGS,
	AR = avrconfig.AR, ARFLAGS = '-rc',
	LINK = avrconfig.LINK, LINKFLAGS = avrconfig.LFLAGS)
env.PrependENVPath('PATH', avrconfig.EXEC_PATH)    

print env['ENV']['PATH']
print env['PLATFORM'] 
print env['SPAWN']

Export('avrconfig')

objs = LIHU_PrepareBuilding(env)




env.Program(avrconfig.TARGET, objs, PROGSUFFIX='.elf')

LIHU_EndBuilding(avrconfig.TARGET)
